name: Qaave
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.2
  lucide_icons: ^0.257.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  intl: ^0.20.2
  flutter_background_service: ^5.1.0
  confetti: ^0.8.0
  flutter_local_notifications: ^17.1.2
  device_apps: ^2.2.0
  workmanager: ^0.9.0
  share_plus: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6

flutter:
  uses-material-design: true
  
  # 🎨 এখানে ঠিক ২টা স্পেস এবং নিচের ফাইলগুলোতে ৪টা স্পেস দেওয়া হয়েছে
  assets:
    - assets/qaave_logo.png
    - assets/poster1.jpg
    - assets/poster2.jpg
    - assets/poster3.jpg
    - assets/poster4.jpg

# ---------------------------------------------------
# 🚀 APP LOGO CONFIGURATION
# ---------------------------------------------------
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/qaave_logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#F8FAFC"
  image: "assets/qaave_logo.png" # 👈 এখানেও লোগোর পাথ আপডেট করা হলো
  android_12:
    image: "assets/qaave_logo.png"
    color: "#F8FAFC"